name: CI/CD

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    env:
      DATA_DIR: ./data

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Convert data
        uses: jbangdev/jbang-action@v0.114.0
        with:
          script: converter.java

